#!/bin/bash

# find total number of windows on current space that are not floating, not sticky, not minimized, but are visible.
TOTAL="$(yabai -m query --windows --space | jq '.[] | select(.floating==0) | select(.sticky==0) | select(.visible==1) | select(.minimized==0) | length % 23 + 1' | wc -l)"

# if the total is greater than 1, set padding, else disable padding.
if [[ $TOTAL -gt 1 ]]; then  
  yabai -m space --gap abs:20 && \
  yabai -m space --padding abs:20:20:20:20 
else 
  yabai -m space --gap abs:0 && \
  yabai -m space --padding abs:0:0:0:0
fi
